---
title: "plot_burnin"
author: "Tobias Holden"
date: "5/24/2023"
output: html_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message=F, error=F, warning = F)
library(tidyverse)
library(data.table)
pal20 <- c('#e6194b', '#3cb44b', '#ffe119', '#4363d8', '#f58231', '#911eb4', '#46f0f0', '#f032e6', '#bcf60c', '#fabebe', '#008080', '#e6beff', '#9a6324', '#fffac8', '#800000', '#aaffc3', '#808000', '#ffd8b1', '#000075', '#808080', '#ffffff', '#000000')
```

### Load Spatial Report Snapshots

```{r}
### Update with post-analysis experiment ID

exp_id = '79158f28-223d-46a0-8135-1d3b9a12eba6'
out_root = paste("simulation_output",exp_id, sep='/')
spatial_filename = 'SpatialReportMalariaFiltered.csv'

burnin <- fread(paste(out_root,spatial_filename,sep='/'))

# Load reference data
ref <- fread(paste('simulation_inputs','reference_data','cluster_calibration_targets.csv',sep='/'))

# Placeholder for Checkpoint Comparisons
checkpoint_fname = paste(out_root,"checkpoint.csv",sep='/')
```

```{r}
burnin %>% 
  ggplot(aes(x=time, y=PCR_Parasite_Prevalence)) +
  geom_path(aes(group=interaction(xTLH,cm_cov_u5, Run_Number))) +
  facet_wrap(~node)
  
  
```

