---
title: "indie_plots"
author: "Tobias Holden"
date: "5/2/2023"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(data.table)
root <- 'simulation_output'
experiment <- 'checkpoint_test'
exp_id <- '3e48d65c-391d-4916-89d4-a8bc774a78e1'

path <- paste(root,experiment,exp_id,sep='/')
```

```{r}

events <- fread(paste(path,"CountedEvents.csv",sep='/'))
spatial_df <- fread(paste(path,"SpatialReportMalariaFiltered.csv",sep='/'))

colnames(spatial_df) <- toupper(colnames(spatial_df))
colnames(events) <- toupper(colnames(events))

common_cols <- intersect(colnames(spatial_df),colnames(events))

combo <- inner_join(spatial_df, events, by=common_cols)


remove(events)
remove(spatial_df)


common_cols <- common_cols[!(common_cols %in% ignore_vars)]
pin <- length(common_cols)+1


combo[ , -c("RUN_NUMBER","EXPERIMENT")] -> combo
end <- ncol(combo)

combo %>%
  relocate(common_cols) %>%
  gather(key="variable",value="value", pin:end) %>%
  group_by_at(c(common_cols,"variable")) %>%
  summarize(mean=mean(value),
            sd=sd(value),
            n = n()) -> df


for(var in unique(df$variable)){
  for(n in unique(df$NODE)){
    df %>% 
      filter(NODE==n & variable==var) %>%
      ggplot(aes(x=TIME, y=mean)) +
      geom_path(aes(group=XTLH)) +
      facet_wrap(~CM_COV_U5)
    
    ggsave(paste("node",n,"calibration",var,"mean.png"))
  }
}
```