---
title: "indie_sim_plots"
author: "Tobias Holden"
date: "3/8/2023"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message=F, error=F, warning = F)
library(tidyverse)
library(data.table)
pal20 <- c('#e6194b', '#3cb44b', '#ffe119', '#4363d8', '#f58231', '#911eb4', '#46f0f0', '#f032e6', '#bcf60c', '#fabebe', '#008080', '#e6beff', '#9a6324', '#fffac8', '#800000', '#aaffc3', '#808000', '#ffd8b1', '#000075', '#808080', '#ffffff', '#000000')
```

### Load Spatial Report Snapshots

```{r}
### Update with post-analysis experiment ID

exp_id = 'e4dec631-7f16-4b43-9cab-f0b4b6276cb7'
out_root = paste("simulation_output",exp_id, sep='/')
spatial_filename = 'SpatialReportMalariaFiltered.csv'
event_filename = 'CountedEvents.csv'

SR <- fread(paste(out_root,spatial_filename,sep='/'))
ER <- fread(paste(out_root,event_filename,sep="/"))

# Load reference data
ref <- fread(paste('simulation_inputs','reference_data','cluster_calibration_targets.csv',sep='/'))

# Placeholder for Checkpoint Comparisons
checkpoint_fname = paste(out_root,"checkpoint.csv",sep='/')
```

```{r}

ER %>% rename(time = Time, node = Node) -> ER

inner_join(ER,SR_ranked) -> df
# Get Averages
df[, list(treated=mean(Received_Treatment), smc=mean(Received_SMC), nets=mean(Received_ITN), 
          PCR_Parasite_Prevalence=mean(PCR_Parasite_Prevalence),
          New_Clinical_Cases = mean(New_Clinical_Cases),
          Rainfall=mean(Rainfall),
          Population = mean(Population),
          Bites=mean(Daily_Bites_Per_Human)), 
   keyby=c("node","time","xTLH","cm_cov_u5")] -> SR

```

```{r}

SR %>%
  filter(time %in% ref$time) %>%
  group_by(time, node, xTLH, cm_cov_u5) %>%
  summarize_all(mean) %>%
  left_join(ref, by=c("node","time")) %>%
  mutate(diff=abs(PCR_Parasite_Prevalence-pcr_prevalence)) %>%
  group_by(node, xTLH, cm_cov_u5) %>%
  # Rank by weighted mean error (weighted by number of obs, n)
  summarize(mean_err = mean(diff,na.rm=T),
            weighted_mean_err = weighted.mean(diff,n,na.rm=T)) %>%
  group_by(node) %>%
  mutate(rank = rank(mean_err, ties.method = "random"),
         weighted_rank = rank(weighted_mean_err, ties.method = "random")) %>%
  arrange(rank) -> SR_ranked

# save to checkpoint file
write.csv(x = SR_ranked, file = paste(checkpoint_fname))
```

```{r}

### Plot heatmap of parameter space rankings

SR_ranked %>%
  ggplot(aes(x=log10(xTLH),y=cm_cov_u5, fill=mean_err)) +
  geom_tile(color="white",alpha=1, size=0.5)+
  #geom_tile(aes(color=rank<=rank_limit, 
  #              alpha=rank<=rank_limit, 
  #              size=rank<=rank_limit)) +
  scale_alpha_manual(values=c(0,1)) + 
  scale_color_manual(values=c("white","black"))+
  scale_size_manual(values=c(0,0.5))+
  scale_fill_distiller(palette="Spectral") +
  facet_wrap(~paste("Cluster",node),ncol=2) +
  coord_fixed() +
  ylab("Case Management U5") + xlab("log(xTLH)") +
  labs(fill="|simulation-trial|") +
  theme(legend.position="top") +
  guides(fill=guide_colorbar(title.position = "top",
                             title.hjust=0.5,
                             barwidth = unit(10,"cm")))

ggsave(paste(out_root,paste("Parameter Ranking.png",sep = '_'),sep="/"))

SR_ranked %>%
  ggplot(aes(x=log10(xTLH),y=cm_cov_u5, fill=weighted_mean_err)) +
  geom_tile(color="white",alpha=1, size=0.5)+
  #geom_tile(aes(color=rank<=rank_limit, 
  #              alpha=rank<=rank_limit, 
  #              size=rank<=rank_limit)) +
  scale_alpha_manual(values=c(0,1)) + 
  scale_color_manual(values=c("white","black"))+
  scale_size_manual(values=c(0,0.5))+
  scale_fill_distiller(palette="Spectral") +
  facet_wrap(~paste("Cluster",node),ncol=2) +
  coord_fixed() +
  ylab("Case Management U5") + xlab("log(xTLH)") +
  labs(fill="|simulation-trial|") +
  theme(legend.position="top") +
  guides(fill=guide_colorbar(title.position = "top",
                             title.hjust=0.5,
                             barwidth = unit(10,"cm")))
ggsave(paste(out_root,paste("Parameter Ranking (weighted).png",sep = '_'),sep="/"))
```


```{r}

### Ranked Parameter Sets vs. Calibration Data
run_size <- length(unique(ER$Run_Number))

rank_limit <- 20

SR %>%
  left_join(SR_ranked) %>%
  filter(rank <=rank_limit) %>%
  mutate(month = trunc(time/30)) %>%
  group_by(rank, node, month) %>%
  summarize(month_incidence = sum(treated)/mean(Population)) -> SR_incidence
    
  

SR %>%
  left_join(SR_ranked) %>%
  filter(rank <=rank_limit) %>%
  group_by(rank, node) %>%
  ggplot(aes(x=as.Date(time, origin="2011-01-01"))) +
  facet_wrap(~node) +
  geom_path(aes(y=PCR_Parasite_Prevalence, linetype = "PCR Prevalence", group=rank)) +
  geom_point(aes(y=ifelse(smc==0,NA,1), color="SMC")) +
  geom_point(aes(y=ifelse(nets==0,NA,1), color="ITN")) +
  geom_path(data=SR_incidence, aes(x=as.Date(month*30,origin="2011-01-01"), y=month_incidence, group=rank, linetype="Monthly Incidence")) 



SR %>%
  left_join(SR_ranked) %>%
  filter(weighted_rank <=rank_limit) %>%
  mutate(month = trunc(time/30)) %>%
  group_by(weighted_rank, node, month) %>%
  summarize(month_incidence = sum(treated)/mean(Population)) -> SR_incidence

SR %>%
  left_join(SR_ranked) %>%
  filter(weighted_rank <=rank_limit) %>%
  group_by(weighted_rank, node) %>%
  ggplot(aes(x=as.Date(time, origin="2011-01-01"))) +
  facet_wrap(~node) +
  geom_path(aes(y=PCR_Parasite_Prevalence, linetype = "PCR Prevalence", group=weighted_rank)) +
  geom_point(aes(y=ifelse(smc==0,NA,1), color="SMC")) +
  geom_point(aes(y=ifelse(nets==0,NA,1), color="ITN")) +
  geom_path(data=SR_incidence, aes(x=as.Date(month*30, origin="2011-01-01"), y=month_incidence, group=weighted_rank, linetype="Monthly Incidence"))

```

```{r}

for(rl in c(2,5,10,20,30))
{
  rank_limit <- rl
  SR %>% 
    left_join(SR_ranked, by=c("node","xTLH","cm_cov_u5")) %>%
    filter(time >= max(time)-3*365) %>%
    filter(rank<=rank_limit)  %>%
    group_by(node,time) %>%
    summarize(CI = 1.96*sd(PCR_Parasite_Prevalence)/sqrt(rank_limit*run_size),
              PCR_Parasite_Prevalence=mean(PCR_Parasite_Prevalence)) %>%
    ggplot(aes(x=as.Date(time, origin="2011-01-01"),
               y=PCR_Parasite_Prevalence)) +
    geom_point(data=ref, aes(x=as.Date(time, origin="2011-01-01"), y=pcr_prevalence), color="black",fill="white",shape=21, group=NA) +
    facet_wrap(~paste("Cluster",node), ncol=2) +
    geom_ribbon(aes(ymin=PCR_Parasite_Prevalence-CI, ymax=PCR_Parasite_Prevalence+CI), fill="blue", alpha=0.25) +
    geom_path(color="blue") +
    xlab("") +
    scale_y_continuous(limits = c(0,NA)) +
    ggtitle(paste("Top",rank_limit,"ranked parameter sets"), paste(run_size,"runs each")) +
    theme_minimal() +
    labs(size=NULL) +
    theme(legend.position=c(0.15,0.05), 
          legend.direction = "horizontal") -> p
  print(p)
  ggsave(paste(out_root,paste("Top",rank_limit,"ranked parameter sets.png",sep = '_'),sep="/"))

  SR %>% 
    left_join(SR_ranked, by=c("node","xTLH","cm_cov_u5")) %>%
    filter(time >= max(time)-3*365) %>%
    filter(weighted_rank<=rank_limit)  %>%
    group_by(node,time) %>%
    summarize(CI = 1.96*sd(PCR_Parasite_Prevalence)/sqrt(rank_limit*run_size),
              PCR_Parasite_Prevalence=mean(PCR_Parasite_Prevalence)) %>%
    ggplot(aes(x=as.Date(time, origin="2011-01-01"),
               y=PCR_Parasite_Prevalence)) +
    geom_point(data=ref, aes(x=as.Date(time, origin="2011-01-01"), y=pcr_prevalence, size=n), color="black",fill="white",shape=21, group=NA) +
    facet_wrap(~paste("Cluster",node), ncol=2) +
    geom_ribbon(aes(ymin=PCR_Parasite_Prevalence-CI, ymax=PCR_Parasite_Prevalence+CI), fill="blue", alpha=0.25) +
    geom_path(color="blue") +
    xlab("") +
    scale_y_continuous(limits = c(0,NA)) +
    ggtitle(paste("Top",rank_limit,"ranked parameter sets (weighted)"), paste(run_size,"runs each")) +
    theme_minimal() +
    labs(size=NULL) +
    theme(legend.position=c(0.15,0.05), 
          legend.direction = "horizontal") -> q
  print(q)
  ggsave(paste(out_root,paste("Top",rank_limit,"ranked parameter sets (weighted).png",sep = '_'),sep="/"))

}

# Stacked Plots

ignore_vars <- c("Run_Number","experiment","mean_err", "weighted_mean_err", "weighted_rank")
lasso <- c("node","time","xTLH","cm_cov_u5","rank")
node_list <- factor(paste("Node",unique(SR$node)))
rank_limit=5
SR_ranked %>%
  filter(rank<=rank_limit) %>%
  left_join(SR, by = c("node","xTLH","cm_cov_u5")) %>%
  select(-ignore_vars) %>%
  gather(key="variable", value="value", -lasso) %>%
  group_by(variable,node, time, xTLH, cm_cov_u5, rank) %>%
  summarize(value=mean(value))%>%
  ggplot(aes(x=time, y=value)) +
  facet_grid(gsub("_"," ",variable)~factor(paste("Node",node),levels=node_list), scales="free") +
  geom_path(aes(group=rank, color=rank), alpha=0.7)

```

```{r}
SR_ranked %>%
  filter(rank<=5) %>%
  left_join(SR, by=c("node","xTLH","cm_cov_u5")) %>%
  select(time, rank, New_Clinical_Cases, Run_Number) %>%
  mutate(time=time-min(time)) %>%
  filter(time<365) %>%
  mutate(date=as.Date(time, origin="2018-01-01")) %>%
  mutate(month_year=format.Date(date, format="%Y-%m-01")) %>%
  group_by(rank,month_year,Run_Number) %>%
  summarize(cases = sum(New_Clinical_Cases)) %>%
  ggplot(aes(as.Date(month_year), y=cases, color=rank)) +
  geom_point(size=3) +
  geom_line(size=1, aes(group=interaction(Run_Number,rank))) +
  theme_minimal() +
  xlab("") + ylab("") +
  scale_x_date(date_breaks = "2 months", date_minor_breaks = "1 month", 
               date_labels = "%b %y") +
  facet_wrap(~rank)

head(SR_ranked)
  
SR %>% 
  select(time,Rainfall) %>%
  filter(time %in% seq(min(time),min(time)+365,1)) %>%
  group_by(time) %>%
  summarize_all(mean) %>%
  ggplot(aes(x=as.Date(time,origin="2011-01-01"), y=Rainfall)) +
  #ggplot(aes(x=as.Date(time,origin="2011-01-01"), y=Rainfall)) +
  geom_path()


  
```

